---
# This is an example playbook to execute Ansible tests.
- name: Verify ubuntu
  hosts: ubuntu
  gather_facts: false
  tasks:
  - name: Restart elastic
    sysvinit:
      name: elasticsearch
      state: restarted
  - name: Wait port 9200
    wait_for:
      host: 0.0.0.0
      port: 9200
      state: started
  - name: Restart kibana
    ansible.builtin.service:
      name: kibana
      state: restarted
  - name: Wait port 5601
    wait_for:
      host: 0.0.0.0
      port: 5601
- name: Verify centos  
  hosts: centos7
  gather_facts: false
  tasks:
  - name: Restart elastic
    sysvinit:
      name: elasticsearch
      state: restarted
  - name: Wait port 9200
    wait_for:
      host: 0.0.0.0
      port: 9200
      state: started
  - name: Restart kibana
    sysvinit:
      state: restarted
      name: kibana
  - name: Wait port 5601
    wait_for:
      host: 0.0.0.0
      port: 5601
      state: started
- name: Verify all
  hosts: all
  gather_facts: false
  tasks:
  - name: Check return code
    uri:
      url: http://127.0.0.1:5601/app/home

